// vue/src/App.vue
<template>
  <main class="main">
    <div>
      <RouterView />
      <NavBar />
    </div>
  </main>
</template>

<script setup lang="ts">
import { watch, watchEffect } from 'vue';
import { RouterView } from 'vue-router'
import { useAuth0 } from '@auth0/auth0-vue';
import { storeToRefs } from 'pinia'
import { useMainStore } from '@/store';

import NavBar from './components/NavBar.vue';

const { isAuthenticated, isLoading, idTokenClaims, getAccessTokenSilently } = useAuth0();
const store = useMainStore();
const { email, token } = storeToRefs(store);

console.log(`App load/auth: ${isLoading.value}/${isAuthenticated.value}`);

// get token details as soon as the user is authenticated
watch([isAuthenticated, idTokenClaims], ([newIsAuth, newIdClaims]) => {
  console.log(`isAuthenticated updated: ${newIsAuth}`);
  console.log(`idTokenClaims present: ${newIdClaims ? true : false}`);

  if (newIsAuth && newIdClaims) {
    addTokenClaimsToStore();
  }
});

/// copy token details to the store
async function addTokenClaimsToStore() {
  if (!isAuthenticated.value) {
    console.log("Cannot update token - not authenticated");
    return;
  }

  email.value = idTokenClaims.value?.email;
  token.value = idTokenClaims.value?.__raw;

}

// attempt to get a new token silently
(async () => {
  console.log("Attempting to get a new token silently");
  try {
    const newToken = await getAccessTokenSilently({ detailedResponse: true });
  } catch (e) {
    console.log("Failed to get token silently");
  }
})();

</script>

// react-scr/components/app.js
import { useEffect } from "react";
import { useLocation, Outlet } from "react-router-dom";
import { useAuth0 } from '@auth0/auth0-react'
import { LAST_AUTH_TIMESTAMP } from "./bookDetails.js";

import Navbar from "./navbar.js";

export default function App() {

  const location = useLocation();
  const { isAuthenticated, isLoading, loginWithRedirect, getAccessTokenSilently } = useAuth0();

  useEffect(() => {

    console.log(`App load/auth: ${isLoading}/${isAuthenticated}`);

    // save auth details in the localStorage
    if (!isLoading) {
      if (isAuthenticated) {
        localStorage.setItem(LAST_AUTH_TIMESTAMP, Date.now());
        console.log("Auth status updated in LS");
      }
      else {
        console.log("Not authenticated");

        (async () => {

          // log in the user if was logged in before
          const lastAuth = localStorage.getItem(LAST_AUTH_TIMESTAMP);
          console.log(`Last auth/auth'd: ${lastAuth}/${isAuthenticated}`);
          if (lastAuth && !isAuthenticated) {

            console.log("User was logged in before, logging in again");
            try {
              const accessToken = await getAccessTokenSilently();
              console.log(`Access token: ${accessToken}`);
            } catch (e) {
              console.log(`Error getting access token: ${e}`);
              await loginWithRedirect({
                appState: {
                  returnTo: window.location.pathname,
                },
              })
            }
          }
        })();
      }
    }

  }, [isLoading, isAuthenticated]);

  return (
    <div className="main">
      <div>
        <Outlet />
        <Navbar />
      </div>
    </div>
  );
};
